apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rpbbj2ljs-nodejs 
  janus-idp.io/tekton: rpbbj2ljs-nodejs
  backstage.io/kubernetes-id: rpbbj2ljs-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rpbbj2ljs-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml