apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rpbbj2ljs-nodejs-gitops
  description: This is GitOps manifest for rpbbj2ljs-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=rpbbj2ljs-nodejs
    backstage.io/kubernetes-id: rpbbj2ljs-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: rpbbj2ljs-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:rpbbj2ljs-nodejs
